project:
  type: website

website:
  title: "COFINFAD Lab"
  navbar:
    right: 
    - text: "About"
    - text: "Shiny App"
    - text: "Project"
      menu: 
      - text: "Project Proposal"
        href: "Proposal.html"
      - text: "Meeting Minutes"
        href: "Minutes.html"

format:
  html:
    theme:
      - cosmo
    css: styles.css  
    page-layout: full
    toc: true
    toc-title: "On this page"
    smooth-scroll: true
    number-sections: true

editor: visual

